name: update workflow
on: 
  workflow_dispatch:
jobs:
  job_one:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ../pub
            cd arigau.github.io
            git pull
